version: '3'

services:

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=tp

  php:
    build : 
      context: .
      dockerfile: Dockerfile
    environment:
      - PHP_EXTENSIONS=pdo_mysql
    ports:
      - 30000:80
    volumes: 
      - './sources/html_php:/home/user/sources'

  adminer:
    image: adminer
    ports:
      - 50000:8080

  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025
      - 1025:1025
